### 1. LOCAL EKF (Odom Frame) - Sadece IMU ve Tekerlek Odom ###
ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom # Local EKF'in dünyası odom'dur

    # ODOMETRY (Tekerlek)
    odom0: /vehicle/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # IMU
    imu0: /vehicle/imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10

### 2. GLOBAL EKF (Map Frame) - IMU + Tekerlek + GPS ###
ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map # Global EKF'in dünyası map'tir

    # ODOMETRY (Tekerlek)
    odom0: /vehicle/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10

    # IMU
    imu0: /vehicle/imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: false

    # GPS ODOMETRY (Navsat Transform'dan gelecek veri)
    odom1: /odometry/gps
    odom1_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

### 3. NAVSAT TRANSFORM (GPS -> X/Y Çevirici) ###
navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0 # Türkiye için yaklaşık 0.09 ama 0 kalsın şimdilik
    yaw_offset: 0.0 # IMU kuzeyi ile Harita kuzeyi farkı (Simülasyonda 0)
    zero_altitude: true
    broadcast_cartesian_transform: true # GPS->Map dönüşümünü yayınla
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
