ekf_filter_node:
  ros__parameters:

    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    output_topic: /odometry/local

    

    odom0: /odom
    imu0: /imu

